 #设置应用服务的端口号
 server:
  port: ${random.int[10000,19999]}
 #redis配置
 spring:
    redis:
      host: 203.195.160.69
      port: 6379
      # REDIS (RedisProperties)
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器连接密码（默认为空）
      password: Zy$13600199290
      # 连接池最大连接数（使用负值表示没有限制）
      # 连接超时时间（毫秒）
      timeout: 0
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0